# Generated by Django 3.1.3 on 2020-12-09 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_profile_governmentid'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='status',
            field=models.CharField(choices=[('Pending', 'P'), ('Verfied', 'V')], default='Pending', max_length=50),
        ),
    ]
