# Generated by Django 3.1.3 on 2020-12-11 05:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_reading'),
    ]

    operations = [
        migrations.DeleteModel(
            name='reading',
        ),
    ]
