# Generated by Django 3.1.3 on 2020-12-23 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='reading',
            name='identity_verfied',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='reading',
            name='mask_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='reading',
            name='pulserate',
            field=models.DecimalField(decimal_places=2, default=8, max_digits=4),
        ),
    ]
