# Generated by Django 3.1.3 on 2020-12-23 10:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0002_auto_20201223_1614'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reading',
            old_name='pulserate',
            new_name='pulse_rate',
        ),
    ]
